# This example uses a host mounted directory that is created/used relative to this
# location of this compose file.

version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: creative
      DIFFICULTY: normal
      LEVEL_TYPE: flat
      ALLOW_CHEATS: true
      DEFAULT_PLAYER_PERMISSION_LEVEL: operator
    ports:
      - 19132:19132/udp
    volumes:
      - ./data:/data
      - ./development_behavior_packs/my_first_pack_BP:/data/development_behavior_packs/my_first_pack_BP
      - ./development_resource_packs/my_first_pack_RP:/data/development_resource_packs/my_first_pack_RP
      - ./world_behavior_packs.json:/data/worlds/Bedrock level/world_behavior_packs.json
      - ./world_resource_packs.json:/data/worlds/Bedrock level/world_resource_packs.json
    stdin_open: true
    tty: true
