# This example uses a host mounted directory that is created/used relative to this
# location of this compose file.

version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: creative
      DIFFICULTY: normal
      LEVEL_TYPE: flat
    ports:
      - 19132:19132/udp
    volumes:
      - ./data:/data
      - ./development_behavior_packs:/development_behavior_packs
      - ./development_resource_packs:/development_resource_packs
      - ./development_skin_packs:/development_skin_packs
    stdin_open: true
    tty: true
